name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-east4
  SERVICE_NAME: users

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.SA_EMAIL }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: setup cloud sdk
        uses: google-github-actions/setup-gcloud@v1

      - name: docker auth
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: "Build and push container"
        run: |-
          docker build -t "${{ env.RUN_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.RUN_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.RUN_REGION }}
          image: "${{ env.RUN_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
