name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    RUN_REGION: us-east4
    SERVICE_NAME: users

jobs:
    setup-build-deploy:
        name: Setup, Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - id: auth
              uses: google-github-actions/auth@v1
              with:
                  version: '416.0.0'
                  service_account_email: ${{ secrets.SA_EMAIL }}
                  service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            - name: setup cloud sdk
              uses: google-github-actions/setup-gcloud@v1

            - name: gcloud Set up
              run: |
                   gcloud config set project $PROJECT_ID

            - name: Build
              run: |
                   gcloud builds submit -t us-east4-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

            - name: Deploy
              run: |
                   gcloud run deploy $SERVICE_NAME \
                    --region $RUN_REGION
                    --image us-east4-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
                    --platform managed
