name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    RUN_REGION: us-east4
    SERVICE_NAME: users

jobs:
    setup-build-deploy:
        name: Setup, Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - id: auth
              uses: google-github-actions/auth@v1
              with:
                  service_account: ${{ secrets.SA_EMAIL }}
                  credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            - name: setup cloud sdk
              uses: google-github-actions/setup-gcloud@v1
              with:
                project_id: $PROJECT_ID

            - name: docker auth
              run: |
                   gcloud auth configure-docker us-east4-docker.pkg.dev

                   - name: 'Build and push container'
                   run: |-
                     docker build -t "$RUN-REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }}" .
                     docker push "$RUN/REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }}"