name: Test API

on: [push]

jobs:
  run-tests:
    name: Run API tests
    runs-on: ubuntu-latest

    steps:
      - name: Install requirements
        run: |
            pip install -r requirements.txt

      - name: Testing
        run: |
          pytest
